import { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    home: 'Home',
    cars: 'Cars',
    login: 'Login',
    darkMode: 'Dark Mode',
    allRightsReserved: 'All rights reserved',
    email: 'Email',
    password: 'Password',
    welcome: 'Welcome to Car Rental',
    rentPremiumCars: "Rent Premium Cars with Comfort",
    heroSubtitle: "Choose from our exclusive collection and enjoy premium service",
    exploreCollection: "Explore Fleet",
    whyChooseUs: "Why Choose Our Service",
    featureTitle1: "Premium Fleet",
    featureDesc1: "50+ luxury vehicles regularly maintained",
    featureTitle2: "Best Rates",
    featureDesc2: "Competitive prices with no hidden fees",
    featureTitle3: "Full Coverage",
    featureDesc3: "Comprehensive insurance included",
    fixedPrepayment: "Prepayment for all cars is fixed, only 50 000 ₸",
    howToBook: "How to Book a Car",
    stepTitle1: "Registration",
    stepDesc1: "Create an account with your name and email",
    stepTitle2: "Login",
    stepDesc2: "Sign in using your email and password",
    stepTitle3: "Choose a Car",
    stepDesc3: "Select a vehicle from our fleet",
    stepTitle4: "Select Dates",
    stepDesc4: "Pick your rental start and end dates",
    stepTitle5: "Payment",
    stepDesc5: "Complete booking with your preferred payment method",
    howToBook: "How to Book a Car",
    stepTitle1: "Registration",
    stepDesc1: "Create an account with your name and email",
    stepTitle2: "Login",
    stepDesc2: "Sign in using your email and password",
    stepTitle3: "Choose a Car",
    stepDesc3: "Select a vehicle from our fleet",
    stepTitle4: "Select Dates",
    stepDesc4: "Pick your rental start and end dates",
    stepTitle5: "Payment",
    stepDesc5: "Complete booking with your preferred payment method",
    availableCars: 'Available Cars',
    loading: 'Loading...',
    error: 'Error',
    booking: 'Booking',
    selectDates: 'Select dates',
    startDate: 'Start date',
    endDate: 'End date',
    totalPrice: 'Total price',
    days: 'days',
    cancel: 'Cancel',
    confirmBooking: 'Confirm Booking',
    processing: 'Processing...',
    selectBothDates: 'Please select both dates',
    invalidDateRange: 'Invalid date range',
    bookingError: 'Booking error occurred',
    bookingSuccess: 'Booking successful!',
    year: 'Year',
    pricePerDay: 'Price per day',
    close: 'Close',
    loginToBook: 'Please sign in to book a car',
    signIn: 'Sign In',
    register: 'Register',
    loginRequired: 'You need to login to make a booking',
    loginTitle: 'Login',
    registerTitle: 'Register',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    nameLabel: 'Name',
    loginButton: 'Sign In',
    registerButton: 'Create Account',
    noAccount: 'Don\'t have an account?',
    haveAccount: 'Already have an account?',
    errorLogin: 'Login error',
    errorRegistration: 'Registration error',
    year: 'Year',
    filterByBrand: "Filter by brand",
    allBrands: "All brands",
    sortBy: "Sort by",
    brand: "A-Z",
    year: "Year",
    price: "Price",

    adminPanel: 'Admin Panel',
    allBookings: 'All Bookings',
    myBookings: 'My Bookings',
    reviews: 'Reviews',
    bookings: 'Bookings',
    profile: 'Profile',
    logout: 'Logout',
    confirmPasswordLabel: 'Repeat the password',

    nameRequired: 'Name is required',
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    registrationSuccess: 'An error occurred during registration',
    registrationFailed: 'Registration failed',
    registrationError: 'Registration successful! ',
    redirectingToLogin: 'Redirecting to login page...',
    registering: 'Registering...',
    // ReviewsPage
    reviewsTitle: 'Service Reviews',
    leaveReview: 'Leave Your Review',

    // SiteReviewForm
    authRequired: 'Authorization required to submit review',
    ratingValidation: 'Please select rating between 1-5 stars',
    reviewThanks: 'Thank you for your review!',
    submitError: 'Submission error',
    unknownError: 'Unknown error',
    yourRating: 'Your Rating',
    ratingLabel: 'Rate {stars} stars',
    comment: 'Comment',
    commentPlaceholder: 'Your review...',
    maxSymbols: 'Max 500 symbols',
    submitReview: 'Submit Review',

    // SiteReviewList
    overallRating: 'Service Rating',
    basedOn: 'Based on all reviews',
    loadingReviews: 'Loading reviews...',
    noReviews: 'No reviews yet',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    goToPage: 'Go to page {page}',
    previous: '← Previous',
    next: 'Next →',
    personalInfo: 'Personal Information',
    name: 'Name',
    role: 'Role',
    admin: 'Administrator',
    user: 'User',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    passwordMismatch: 'Passwords do not match',
    passwordLength: 'Password must be at least 6 characters',
    passwordChangeSuccess: 'Password changed successfully',
    passwordChangeError: 'Error changing password',
    changePasswordButton: 'Change Password',
    loading: 'Loading...',
    myBookings: 'My Bookings',
    noBookings: 'You have no active bookings',
    bookingPeriod: 'Booking period',
    totalPrice: 'Total price',
    status: 'Status',
    active: 'Active',
    cancelled: 'Cancelled',
    cancelBooking: 'Cancel Booking',
    year: 'Year',
    pricePerDay: 'Price per day',
    totalAmount: "Total Amount",
    paymentMethod: "Payment Method",
    creditCard: "Credit Card",
    paypal: "PayPal",
    bankTransfer: "Bank Transfer",
    cardNumber: "Card Number",
    expiryDate: "Expiry Date",
    cvv: "CVV",
    cardHolder: "Card Holder",
    fullName: "Full Name",
    confirmPayment: "Confirm Payment",
    cancel: "Cancel",
    processing: "Processing payment",
    paymentSuccess: "Payment successful!",
    paymentFailed: "Payment failed. Please try again.",
    paymentStatus: "Payment Status",
    paid: "Paid",
    notPaid: "Not Paid",
    payNow: "Pay Now",
    paymentFor: "Payment for",
    deposit: 'Deposit',
    paid: 'Paid',
    notPaid: 'Not paid',
    payDeposit: 'Pay Deposit',
    cardNumber: 'Card Number',
    cardHolder: 'Card Holder',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    cancel: 'Cancel',
    pay: 'Pay',
    deposit: 'Deposit',
    paid: 'Paid',
    notPaid: 'Not paid',
    payDeposit: 'Pay Deposit (50,000 ₸)'




  },
  ru: {
    deposit: 'Залог',
    paid: 'Оплачен',
    notPaid: 'Не оплачен',
    payDeposit: 'Оплатить залог',
    cardNumber: 'Номер карты',
    cardHolder: 'Имя владельца',
    expiryDate: 'Срок действия',
    cvv: 'CVV код',
    cancel: 'Отмена',
    pay: 'Оплатить',
    deposit: 'Залог',
    paid: 'Оплачен',
    notPaid: 'Не оплачен',
    payDeposit: 'Оплатить залог (50,000 ₸)',
    home: 'Главная',
    cars: 'Автомобили',
    login: 'Войти',
    darkMode: 'Тёмная тема',
    allRightsReserved: 'Все права защищены',
    email: 'Электронная почта',
    password: 'Пароль',
    welcome: 'Добро пожаловать в аренду автомобилей',
    rentPremiumCars: "Аренда премиальных автомобилей",
    heroSubtitle: "Выберите автомобиль из нашей коллекции и наслаждайтесь поездкой",
    exploreCollection: "Смотреть автопарк",
    whyChooseUs: "Преимущества нашего сервиса",
    featureTitle1: "Премиальный автопарк",
    featureDesc1: "Более 50 автомобилей в отличном состоянии",
    featureTitle2: "Лучшие цены",
    featureDesc2: "Доступные тарифы без скрытых платежей",
    featureTitle3: "Полная страховка",
    featureDesc3: "Комплексная страховка включена",
    fixedPrepayment: "Предоплата за все автомобили фиксированная, всего 50 000 ₸",
    howToBook: "Как забронировать автомобиль",
    stepTitle1: "Регистрация",
    stepDesc1: "Создайте аккаунт, указав имя и email",
    stepTitle2: "Вход",
    stepDesc2: "Авторизуйтесь, используя email и пароль",
    stepTitle3: "Выбор авто",
    stepDesc3: "Выберите автомобиль из нашего автопарка",
    stepTitle4: "Выбор даты",
    stepDesc4: "Укажите дату начала и окончания аренды",
    stepTitle5: "Оплата",
    stepDesc5: "Оплатите бронирование удобным способом",
    availableCars: 'Доступные автомобили',
    loading: 'Загрузка...',
    error: 'Ошибка',
    booking: 'Бронирование',
    selectDates: 'Выберите даты',
    startDate: 'Начало',
    endDate: 'Окончание',
    totalPrice: 'Общая стоимость',
    days: 'дней',
    cancel: 'Отмена',
    confirmBooking: 'Подтвердить бронь',
    processing: 'Обработка...',
    selectBothDates: 'Выберите обе даты',
    invalidDateRange: 'Некорректный период',
    bookingError: 'Ошибка бронирования',
    bookingSuccess: 'Бронирование успешно!',
    year: 'Год',
    pricePerDay: 'Цена за день',
    close: 'Закрыть',
    loginToBook: 'Для бронирования войдите в систему',
    signIn: 'Войти',
    register: 'Зарегистрироваться',
    loginRequired: 'Для бронирования необходимо авторизоваться',
    loginTitle: 'Вход в систему',
    registerTitle: 'Регистрация',
    emailLabel: 'Email',
    passwordLabel: 'Пароль',
    nameLabel: 'Имя',
    loginButton: 'Войти',
    registerButton: 'Зарегистрироваться',
    noAccount: 'Нет аккаунта?',
    haveAccount: 'Уже есть аккаунт?',
    errorLogin: 'Ошибка при входе',
    errorRegistration: 'Ошибка регистрации',
    filterByBrand: "Фильтр по марке",
    allBrands: "Все марки",
    sortBy: "Сортировать по",
    brand: "A-Z",
    year: "Год выпуска",
    price: "Цене",
    adminPanel: 'Админ-панель',
    allBookings: 'Все бронирования',
    myBookings: 'Мои бронирования',
    reviews: 'Отзывы',
    bookings: 'Бронирования',
    profile: 'Профиль',
    logout: 'Выход',
    confirmPasswordLabel: 'Повторите пароль',
    nameRequired: 'Имя обязательно',
    emailRequired: 'Email обязателен',
    passwordRequired: 'Пароль обязателен',
    passwordMismatch: 'Пароли не совпадают',
    passwordTooShort: 'Пароль должен быть не менее 6 символов',
    registrationSuccess: 'Произошла ошибка при регистрации',
    registrationFailed: 'Ошибка регистрации',
    registrationError: 'Регистрация прошла успешно!',
    redirectingToLogin: 'Перенаправляем на страницу входа...',
    registering: 'Регистрируем...',
    reviewsTitle: 'Отзывы о нашем сервисе',
    leaveReview: 'Оставьте свой отзыв',
  
    // SiteReviewForm
    authRequired: 'Для отправки отзыва требуется авторизация',
    ratingValidation: 'Пожалуйста, выберите оценку от 1 до 5 звезд',
    reviewThanks: 'Спасибо за ваш отзыв!',
    submitError: 'Ошибка при отправке',
    unknownError: 'Неизвестная ошибка',
    yourRating: 'Ваша оценка',
    ratingLabel: 'Оценка',
    comment: 'Комментарий',
    commentPlaceholder: 'Ваш отзыв...',
    maxSymbols: 'Максимум 500 символов',
    submitReview: 'Отправить отзыв',
  
    // SiteReviewList
    overallRating: 'Общая оценка сервиса',
    basedOn: 'На основе всех отзывов',
    loadingReviews: 'Загрузка отзывов...',
    noReviews: 'Пока нет отзывов',
    previousPage: 'Предыдущая страница',
    nextPage: 'Следующая страница',
    goToPage: 'Перейти на страницу {page}',
    previous: '← Назад',
    next: 'Вперёд →',
    personalInfo: 'Личные данные',
    name: 'Имя',
    role: 'Роль',
    admin: 'Администратор',
    user: 'Пользователь',
    changePassword: 'Смена пароля',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтвердите пароль',
    passwordMismatch: 'Пароли не совпадают',
    passwordLength: 'Пароль должен быть не менее 6 символов',
    passwordChangeSuccess: 'Пароль успешно изменен',
    passwordChangeError: 'Ошибка при изменении пароля',
    changePasswordButton: 'Изменить пароль',
    loading: 'Загрузка...',
    myBookings: 'Мои бронирования',
    noBookings: 'У вас нет активных бронирований',
    bookingPeriod: 'Период бронирования',
    totalPrice: 'Общая стоимость',
    status: 'Статус',
    active: 'Активно',
    cancelled: 'Отменено',
    cancelBooking: 'Отменить бронирование',
    year: 'Год',
    pricePerDay: 'Цена за день',


    payNow: "Оплатить сейчас",
    paymentFor: "Оплата за",
    totalAmount: "Общая сумма",
    paymentMethod: "Способ оплаты",
    creditCard: "Кредитная карта",
    paypal: "PayPal",
    bankTransfer: "Банковский перевод",
    cardNumber: "Номер карты",
    expiryDate: "Срок действия",
    cvv: "CVV",
    cardHolder: "Держатель карты",
    fullName: "Полное имя",
    confirmPayment: "Подтвердить оплату",
    cancel: "Отмена",
    processing: "Обработка платежа",
    paymentSuccess: "Оплата прошла успешно!",
    paymentFailed: "Ошибка оплаты. Пожалуйста, попробуйте еще раз.",
    paymentStatus: "Статус оплаты",
    paid: "Оплачено",
    notPaid: "Не оплачено"



  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage(prev => (prev === 'en' ? 'ru' : 'en'));
  };

  const t = key => translations[language][key];

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);